# Generated by Django 3.1.4 on 2020-12-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. Emails MUST be UNIQUE.', max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
